version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/videohosting
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6380
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - database
      - redis

  redis:
    image: redis:7.0
    command: redis-server --port 6380
    ports:
      - "6380:6380"

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: videohosting
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
