FROM openjdk:17-jdk-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ffmpeg && apt-get clean && apt-get install -y maven && rm -rf /var/lib/apt/lists/*
COPY pom.xml /app

RUN mvn dependency:resolve
COPY . /app
RUN mvn package -DskipTests

EXPOSE 8082
CMD ["java", "-jar", "target/video-hosting-0.0.1-SNAPSHOT.jar"]